/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package attendancemgmtsyst;

/**
 *
 * @author User
 */
public class RegisterLectStud extends javax.swing.JFrame {

    /**
     * Creates new form RegisterLectStud
     */
    public RegisterLectStud() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        RegisterStudBut = new javax.swing.JButton();
        RegisterLectBut = new javax.swing.JButton();
        BackMainMenuBut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Calibri", 2, 24)); // NOI18N
        jLabel1.setText("Register:");

        RegisterStudBut.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        RegisterStudBut.setText("Students");
        RegisterStudBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterStudButActionPerformed(evt);
            }
        });

        RegisterLectBut.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        RegisterLectBut.setText("Lecturers");
        RegisterLectBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterLectButActionPerformed(evt);
            }
        });

        BackMainMenuBut.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        BackMainMenuBut.setText("Back");
        BackMainMenuBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackMainMenuButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 97, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RegisterLectBut)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(RegisterStudBut, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(87, 87, 87))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(BackMainMenuBut)
                                    .addContainerGap()))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addComponent(RegisterStudBut)
                .addGap(18, 18, 18)
                .addComponent(RegisterLectBut)
                .addGap(18, 18, 18)
                .addComponent(BackMainMenuBut)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterStudButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterStudButActionPerformed
         this.setVisible(false);
        RegisterStudent rs = new RegisterStudent();
        rs.setVisible(true);
    }//GEN-LAST:event_RegisterStudButActionPerformed

    private void RegisterLectButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterLectButActionPerformed
         this.setVisible(false);
         RegisterLecturer rl = new RegisterLecturer();
         rl.setVisible(true);
    }//GEN-LAST:event_RegisterLectButActionPerformed

    private void BackMainMenuButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackMainMenuButActionPerformed
         this.setVisible(false);
        AdminMenu am = new AdminMenu();
        am.setVisible(true);
    }//GEN-LAST:event_BackMainMenuButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterLectStud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterLectStud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterLectStud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterLectStud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterLectStud().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackMainMenuBut;
    private javax.swing.JButton RegisterLectBut;
    private javax.swing.JButton RegisterStudBut;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
